### ISSUE TITLE
Move to Anchor

### ISSUE THREAD

**Issue by lefnire** [lefnire/ocdevel#23]
Free hosting, better integration with various services, simple advertising. Will cover Apple feed requirements that Libsyn not doing well.

* [ ] Migrate old rss.xml (waiting for deletion of someone who squatted my feed)
   * Ensure GUIDs & such still work, no duplication of content & destinations.
   * Esp. destinations which I setup manually? (Look into Libsyn>Settings)
* [ ] Redo first episode, mention Gnothi, Patreon, free access & ad-removal
* [ ] Add ads to eps (projects broken, so just import MP3s & insert)
   * Ad-free eps combed into Patreon
* [ ] Also look into Megaphone

See email "Podcasting with Anchor!" if anything needed
